name: Build Binary Artifacts and Sign
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api/source/**'
      - 'client/src/**'
      - 'docs/**'
      - 'Dockerfile'
      - '.github/workflows/build-client.yml'
      - '.github/workflows/build-docs.yml'
      - '.github/workflows/pub-docker.yml'
      - '.github/workflows/build-binary-artifacts.yml'
    tags:
      - 1.**
jobs:
  # build-client:
  #   uses: nuwcdivnpt/stig-manager/.github/workflows/build-client.yml@main
  # build-docs:
  #   uses: nuwcdivnpt/stig-manager/.github/workflows/build-docs.yml@main

  build-binary-artifacts:
    name: Build binary artifacts, sign, export
    # needs:
    #   - build-client
    #   - build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      # - name: Download client distribution
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: client-dist
      #     path: ./client/dist
      # - name: Download documentation
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: docs-build
      #     path: ./docs/_build/html
      - name: Get repository metadata
        id: repo
        uses: actions/github-script@v6
        with:
          script: |
            const repo = await github.rest.repos.get(context.repo)
            return repo.data
      - name: install pkg
        run: |
          sudo npm install -g pkg             
      - name: try existing build script
        id: theCurrentScript
        # uses: actions/github-script@v6
        working-directory: ./api
        run: ./build.sh
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:        
          name: binary-artifacts
          path: ./api/bin/
      - name: Upload archives
        uses: actions/upload-artifact@v3
        with:
          name: binary-archives
          path: ./api/dist/
