name: Build docs
on:
  workflow_dispatch:
  workflow_call:
jobs:
  builder:
    name: builder
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: build image
        with:
          # context: ./docs
          working-directory: ./docs
        run: docker build --tag sphinx-with-requirements .
      -
        name: run image, generating docs
        run: docker run --rm -v ${PWD}:/docs sphinx-with-requirements make html

      # - 
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./docs/
      #     file: ./Dockerfile
      #     push: false
      #     build-args: |
      #       COMMIT_BRANCH=${{ steps.prep.outputs.branch }}
      #       COMMIT_SHA=${{ github.sha }}
      #       COMMIT_TAG=${{ steps.prep.outputs.tag }}
      #       COMMIT_DESCRIBE=${{ steps.prep.outputs.describe }}       
      - 
        name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs-build
          path: ./docs/_build/html
      

